import turtle
import random

s = turtle.Turtle()

#s.hideturtle()
s.speed(50)
total = int(50)
a = int(0)
at = int(140)
bto = int(-25)
btt = int(125)
e = int(10)

#Base
s.penup()
s.goto(0,-100)
s.pendown()
s.circle(100)
s.penup()
s.goto(0,100)
s.pendown()
s.circle(50)
s.penup()
s.goto(0,200)
s.pendown()
s.circle(25)
s.penup()

#Eyes
for i in range(2):
    s.fillcolor("black")
    s.begin_fill()
    s.penup()
    s.goto(e,225)
    s.pendown()
    s.circle(5)
    s.end_fill()
    e = int(e) - int(e) - int(e)

#Buttons Part 1
for i in range(2):
    s.penup()
    s.goto(0,bto)
    s.pendown()
    s.begin_fill()
    s.circle(10)
    s.end_fill()
    bto = int(bto) + int(75)

#Buttons Part 2
for i in range(2):
    s.penup()
    s.goto(0,btt)
    s.pendown()
    s.begin_fill()
    s.circle(10)
    s.end_fill()
    btt = int(btt) + int(45)

#Arms
for i in range(2):
    s.right(a)
    s.penup()
    s.goto(total,150)
    s.pendown()
    s.forward(90)
    s.left(45)
    s.forward(45)
    s.goto(at,150)
    s.right(45)
    s.forward(45)
    s.right(180)
    s.forward(45)
    s.right(225)
    s.forward(45)
    a = int(a) + int(135)
    total = int(total) - int(total) - int(total)
    at = int(at) - int(at) - int(at)

#Hat
s.penup()
s.goto(0,250)
s.pendown()
s.begin_fill()
s.left(45)
s.forward(45)
s.right(180)
s.forward(90)
s.left(180)
s.forward(25)
s.right(90)
s.forward(45)
s.left(180)
s.forward(45)
s.left(180)
s.forward(45)
s.left(90)
s.forward(45)
s.left(90)
s.forward(45)
s.end_fill()

#Title
s.penup()
s.goto(-250, 100)
s.pendown()
s.write("Generic", align='left', font=('Arial', 20, 'underline'))
s.penup()
s.goto(275, 100)
s.pendown()
s.write("Snowman", align='right', font=('Arial', 20, 'underline'))

#Nose
s.fillcolor("Orange")
s.penup()
s.goto(0,215)
s.pendown()
s.begin_fill()
s.left(60)
s.forward(45)
s.right(200)
s.forward(45)
s.left(100)
s.forward(18)
s.end_fill()
s.penup()
s.goto(1,1)
s.pendown()
